// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMessage = "messages"

// Message mapped from table <messages>
type Message struct {
	ID       string    `gorm:"column:id;primaryKey" json:"id"`
	RoomID   string    `gorm:"column:room_id" json:"room_id"`
	SenderID string    `gorm:"column:sender_id" json:"sender_id"`
	Content  string    `gorm:"column:content;not null" json:"content"`
	SentAt   time.Time `gorm:"column:sent_at;default:CURRENT_TIMESTAMP" json:"sent_at"`
	Room     User      `gorm:"foreignKey:messages_room;references:id" json:"room"`
	User     User      `gorm:"foreignKey:messages_user;references:id" json:"user"`
}

// TableName Message's table name
func (*Message) TableName() string {
	return TableNameMessage
}
