// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameRoomMember = "room_members"

// RoomMember mapped from table <room_members>
type RoomMember struct {
	RoomID      string    `gorm:"column:room_id;primaryKey" json:"room_id"`
	UserID      string    `gorm:"column:user_id;primaryKey" json:"user_id"`
	JoinedAt    time.Time `gorm:"column:joined_at;default:CURRENT_TIMESTAMP" json:"joined_at"`
	RoomMembers []User    `gorm:"foreignKey:room_members_user;references:id" json:"room_members"`
	Room        []User    `gorm:"foreignKey:room_members_room;references:id" json:"room"`
}

// TableName RoomMember's table name
func (*RoomMember) TableName() string {
	return TableNameRoomMember
}
